// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type {
  CreateAnalysisRunData,
  CreateAnalysisRunErrors,
  CreateAnalysisRunResponses,
  CreateCaseData,
  CreateCaseErrors,
  CreateCaseResponses,
  DeleteCaseData,
  DeleteCaseErrors,
  DeleteCaseResponses,
  GetAnalysisRunData,
  GetAnalysisRunErrors,
  GetAnalysisRunResponses,
  GetCaseData,
  GetCaseErrors,
  GetCaseResponses,
  GetHealthData,
  GetHealthErrors,
  GetHealthResponses,
  GetRootData,
  GetRootErrors,
  GetRootResponses,
  ListCaseAnalysisRunsData,
  ListCaseAnalysisRunsErrors,
  ListCaseAnalysisRunsResponses,
  ListCasesData,
  ListCasesErrors,
  ListCasesResponses,
  UpdateCaseData,
  UpdateCaseErrors,
  UpdateCaseResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health Check
 */
export const getHealth = <ThrowOnError extends boolean = false>(
  options?: Options<GetHealthData, ThrowOnError>,
): RequestResult<GetHealthResponses, GetHealthErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetHealthResponses, GetHealthErrors, ThrowOnError>({
    url: '/api/health',
    ...options,
  });

/**
 * Get Cases
 */
export const listCases = <ThrowOnError extends boolean = false>(
  options?: Options<ListCasesData, ThrowOnError>,
): RequestResult<ListCasesResponses, ListCasesErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListCasesResponses, ListCasesErrors, ThrowOnError>({
    url: '/api/cases',
    ...options,
  });

/**
 * Create Case
 */
export const createCase = <ThrowOnError extends boolean = false>(
  options: Options<CreateCaseData, ThrowOnError>,
): RequestResult<CreateCaseResponses, CreateCaseErrors, ThrowOnError> =>
  (options.client ?? client).post<CreateCaseResponses, CreateCaseErrors, ThrowOnError>({
    url: '/api/cases',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Case
 */
export const deleteCase = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCaseData, ThrowOnError>,
): RequestResult<DeleteCaseResponses, DeleteCaseErrors, ThrowOnError> =>
  (options.client ?? client).delete<DeleteCaseResponses, DeleteCaseErrors, ThrowOnError>({
    url: '/api/cases/{case_id}',
    ...options,
  });

/**
 * Get Case
 */
export const getCase = <ThrowOnError extends boolean = false>(
  options: Options<GetCaseData, ThrowOnError>,
): RequestResult<GetCaseResponses, GetCaseErrors, ThrowOnError> =>
  (options.client ?? client).get<GetCaseResponses, GetCaseErrors, ThrowOnError>({
    url: '/api/cases/{case_id}',
    ...options,
  });

/**
 * Update Case
 */
export const updateCase = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCaseData, ThrowOnError>,
): RequestResult<UpdateCaseResponses, UpdateCaseErrors, ThrowOnError> =>
  (options.client ?? client).patch<UpdateCaseResponses, UpdateCaseErrors, ThrowOnError>({
    url: '/api/cases/{case_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Case Analysis Runs
 */
export const listCaseAnalysisRuns = <ThrowOnError extends boolean = false>(
  options: Options<ListCaseAnalysisRunsData, ThrowOnError>,
): RequestResult<ListCaseAnalysisRunsResponses, ListCaseAnalysisRunsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ListCaseAnalysisRunsResponses,
    ListCaseAnalysisRunsErrors,
    ThrowOnError
  >({ url: '/api/cases/{case_id}/analysis-runs', ...options });

/**
 * Create Analysis Run
 */
export const createAnalysisRun = <ThrowOnError extends boolean = false>(
  options: Options<CreateAnalysisRunData, ThrowOnError>,
): RequestResult<CreateAnalysisRunResponses, CreateAnalysisRunErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateAnalysisRunResponses,
    CreateAnalysisRunErrors,
    ThrowOnError
  >({ url: '/api/cases/{case_id}/analysis-runs', ...options });

/**
 * Get Analysis Run
 */
export const getAnalysisRun = <ThrowOnError extends boolean = false>(
  options: Options<GetAnalysisRunData, ThrowOnError>,
): RequestResult<GetAnalysisRunResponses, GetAnalysisRunErrors, ThrowOnError> =>
  (options.client ?? client).get<GetAnalysisRunResponses, GetAnalysisRunErrors, ThrowOnError>({
    url: '/api/analysis-runs/{run_id}',
    ...options,
  });

/**
 * Root
 */
export const getRoot = <ThrowOnError extends boolean = false>(
  options?: Options<GetRootData, ThrowOnError>,
): RequestResult<GetRootResponses, GetRootErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetRootResponses, GetRootErrors, ThrowOnError>({
    url: '/',
    ...options,
  });
