// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AnalysisReport
 */
export type AnalysisReport = {
  /**
   * Summary
   */
  summary: string;
  /**
   * Analysis Plan
   */
  analysis_plan: Array<string>;
  /**
   * Assumptions
   */
  assumptions: Array<string>;
  /**
   * Problem
   */
  problem: string;
  /**
   * Target Audience
   */
  target_audience: string;
  /**
   * Audience Segments
   */
  audience_segments: Array<AudienceSegment>;
  /**
   * Value Proposition
   */
  value_proposition: string;
  /**
   * Jtbd
   */
  jtbd: Array<JtbdItem>;
  lean_canvas: LeanCanvas;
  /**
   * Mvp
   */
  mvp: Array<MvpFeature>;
  /**
   * Backlog
   */
  backlog: Array<BacklogItem>;
  /**
   * Roadmap
   */
  roadmap: Array<RoadmapStage>;
  /**
   * Risks
   */
  risks: Array<ProductRisk>;
  critic_review: CriticReview;
  /**
   * Recommendations
   */
  recommendations: Array<string>;
  /**
   * Final Report Markdown
   */
  final_report_markdown: string;
};

/**
 * AnalysisRunRead
 */
export type AnalysisRunRead = {
  /**
   * Id
   */
  id: number;
  /**
   * Case Id
   */
  case_id: number;
  status: AnalysisStatus;
  result: AnalysisReport | null;
  /**
   * Error Message
   */
  error_message: string | null;
  /**
   * Started At
   */
  started_at: string | null;
  /**
   * Finished At
   */
  finished_at: string | null;
  /**
   * Stages
   */
  stages: Array<AnalysisStageRead>;
};

/**
 * AnalysisStageName
 */
export type AnalysisStageName =
  | 'planner'
  | 'market_analyst'
  | 'product_manager'
  | 'critic'
  | 'editor';

/**
 * AnalysisStageRead
 */
export type AnalysisStageRead = {
  /**
   * Id
   */
  id: number;
  name: AnalysisStageName;
  /**
   * Position
   */
  position: number;
  status: AnalysisStatus;
  /**
   * Result
   */
  result: {
    [key: string]: unknown;
  } | null;
  /**
   * Error Message
   */
  error_message: string | null;
  /**
   * Started At
   */
  started_at: string | null;
  /**
   * Finished At
   */
  finished_at: string | null;
};

/**
 * AnalysisStatus
 */
export type AnalysisStatus = 'pending' | 'running' | 'completed' | 'failed';

/**
 * AudienceSegment
 */
export type AudienceSegment = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Needs
   */
  needs: Array<string>;
};

/**
 * BacklogItem
 */
export type BacklogItem = {
  /**
   * Epic
   */
  epic: string;
  /**
   * User Story
   */
  user_story: string;
  /**
   * Acceptance Criteria
   */
  acceptance_criteria: Array<string>;
  priority: BacklogPriority;
};

/**
 * BacklogPriority
 */
export type BacklogPriority = 'must' | 'should' | 'could';

/**
 * CaseCreate
 */
export type CaseCreate = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description: string;
  /**
   * Audience
   */
  audience?: string | null;
  /**
   * Problem
   */
  problem?: string | null;
  stage?: CaseStage;
  /**
   * Analysis Goal
   */
  analysis_goal?: string | null;
};

/**
 * CaseRead
 */
export type CaseRead = {
  /**
   * Id
   */
  id: number;
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description: string;
  /**
   * Audience
   */
  audience: string | null;
  /**
   * Problem
   */
  problem: string | null;
  stage: CaseStage;
  /**
   * Analysis Goal
   */
  analysis_goal: string | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * CaseStage
 */
export type CaseStage = 'idea' | 'validation' | 'prototype' | 'mvp' | 'launched';

/**
 * CaseUpdate
 */
export type CaseUpdate = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Audience
   */
  audience?: string | null;
  /**
   * Problem
   */
  problem?: string | null;
  stage?: CaseStage | null;
  /**
   * Analysis Goal
   */
  analysis_goal?: string | null;
};

/**
 * CriticReview
 */
export type CriticReview = {
  /**
   * Issues
   */
  issues: Array<string>;
  /**
   * Contradictions
   */
  contradictions: Array<string>;
  /**
   * Recommendations
   */
  recommendations: Array<string>;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
  /**
   * Detail
   */
  detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * JTBDItem
 */
export type JtbdItem = {
  /**
   * Situation
   */
  situation: string;
  /**
   * Motivation
   */
  motivation: string;
  /**
   * Expected Outcome
   */
  expected_outcome: string;
};

/**
 * LeanCanvas
 */
export type LeanCanvas = {
  /**
   * Problems
   */
  problems: Array<string>;
  /**
   * Customer Segments
   */
  customer_segments: Array<string>;
  /**
   * Unique Value Proposition
   */
  unique_value_proposition: string;
  /**
   * Solutions
   */
  solutions: Array<string>;
  /**
   * Channels
   */
  channels: Array<string>;
  /**
   * Revenue Streams
   */
  revenue_streams: Array<string>;
  /**
   * Cost Structure
   */
  cost_structure: Array<string>;
  /**
   * Key Metrics
   */
  key_metrics: Array<string>;
  /**
   * Unfair Advantage
   */
  unfair_advantage: string;
};

/**
 * MVPFeature
 */
export type MvpFeature = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  priority: BacklogPriority;
};

/**
 * ProductRisk
 */
export type ProductRisk = {
  /**
   * Description
   */
  description: string;
  level: RiskLevel;
  /**
   * Mitigation
   */
  mitigation: string;
};

/**
 * RiskLevel
 */
export type RiskLevel = 'low' | 'medium' | 'high';

/**
 * RoadmapStage
 */
export type RoadmapStage = {
  /**
   * Name
   */
  name: string;
  /**
   * Goal
   */
  goal: string;
  /**
   * Deliverables
   */
  deliverables: Array<string>;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/health';
};

export type GetHealthErrors = {
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type GetHealthError = GetHealthErrors[keyof GetHealthErrors];

export type GetHealthResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListCasesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/cases';
};

export type ListCasesErrors = {
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type ListCasesError = ListCasesErrors[keyof ListCasesErrors];

export type ListCasesResponses = {
  /**
   * Response Listcases
   *
   * Successful Response
   */
  200: Array<CaseRead>;
};

export type ListCasesResponse = ListCasesResponses[keyof ListCasesResponses];

export type CreateCaseData = {
  body: CaseCreate;
  path?: never;
  query?: never;
  url: '/api/cases';
};

export type CreateCaseErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type CreateCaseError = CreateCaseErrors[keyof CreateCaseErrors];

export type CreateCaseResponses = {
  /**
   * Successful Response
   */
  201: CaseRead;
};

export type CreateCaseResponse = CreateCaseResponses[keyof CreateCaseResponses];

export type DeleteCaseData = {
  body?: never;
  path: {
    /**
     * Case Id
     */
    case_id: number;
  };
  query?: never;
  url: '/api/cases/{case_id}';
};

export type DeleteCaseErrors = {
  /**
   * Case not found
   */
  404: ErrorResponse;
  /**
   * Validation Error
   */
  422: HttpValidationError;
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type DeleteCaseError = DeleteCaseErrors[keyof DeleteCaseErrors];

export type DeleteCaseResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteCaseResponse = DeleteCaseResponses[keyof DeleteCaseResponses];

export type GetCaseData = {
  body?: never;
  path: {
    /**
     * Case Id
     */
    case_id: number;
  };
  query?: never;
  url: '/api/cases/{case_id}';
};

export type GetCaseErrors = {
  /**
   * Case not found
   */
  404: ErrorResponse;
  /**
   * Validation Error
   */
  422: HttpValidationError;
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type GetCaseError = GetCaseErrors[keyof GetCaseErrors];

export type GetCaseResponses = {
  /**
   * Successful Response
   */
  200: CaseRead;
};

export type GetCaseResponse = GetCaseResponses[keyof GetCaseResponses];

export type UpdateCaseData = {
  body: CaseUpdate;
  path: {
    /**
     * Case Id
     */
    case_id: number;
  };
  query?: never;
  url: '/api/cases/{case_id}';
};

export type UpdateCaseErrors = {
  /**
   * Case not found
   */
  404: ErrorResponse;
  /**
   * Validation Error
   */
  422: HttpValidationError;
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type UpdateCaseError = UpdateCaseErrors[keyof UpdateCaseErrors];

export type UpdateCaseResponses = {
  /**
   * Successful Response
   */
  200: CaseRead;
};

export type UpdateCaseResponse = UpdateCaseResponses[keyof UpdateCaseResponses];

export type ListCaseAnalysisRunsData = {
  body?: never;
  path: {
    /**
     * Case Id
     */
    case_id: number;
  };
  query?: never;
  url: '/api/cases/{case_id}/analysis-runs';
};

export type ListCaseAnalysisRunsErrors = {
  /**
   * Case not found
   */
  404: ErrorResponse;
  /**
   * Validation Error
   */
  422: HttpValidationError;
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type ListCaseAnalysisRunsError =
  ListCaseAnalysisRunsErrors[keyof ListCaseAnalysisRunsErrors];

export type ListCaseAnalysisRunsResponses = {
  /**
   * Response Listcaseanalysisruns
   *
   * Successful Response
   */
  200: Array<AnalysisRunRead>;
};

export type ListCaseAnalysisRunsResponse =
  ListCaseAnalysisRunsResponses[keyof ListCaseAnalysisRunsResponses];

export type CreateAnalysisRunData = {
  body?: never;
  path: {
    /**
     * Case Id
     */
    case_id: number;
  };
  query?: never;
  url: '/api/cases/{case_id}/analysis-runs';
};

export type CreateAnalysisRunErrors = {
  /**
   * Case not found
   */
  404: ErrorResponse;
  /**
   * Validation Error
   */
  422: HttpValidationError;
  /**
   * Analysis failed
   */
  500: ErrorResponse;
};

export type CreateAnalysisRunError = CreateAnalysisRunErrors[keyof CreateAnalysisRunErrors];

export type CreateAnalysisRunResponses = {
  /**
   * Successful Response
   */
  201: AnalysisRunRead;
};

export type CreateAnalysisRunResponse =
  CreateAnalysisRunResponses[keyof CreateAnalysisRunResponses];

export type GetAnalysisRunData = {
  body?: never;
  path: {
    /**
     * Run Id
     */
    run_id: number;
  };
  query?: never;
  url: '/api/analysis-runs/{run_id}';
};

export type GetAnalysisRunErrors = {
  /**
   * Analysis run not found
   */
  404: ErrorResponse;
  /**
   * Validation Error
   */
  422: HttpValidationError;
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type GetAnalysisRunError = GetAnalysisRunErrors[keyof GetAnalysisRunErrors];

export type GetAnalysisRunResponses = {
  /**
   * Successful Response
   */
  200: AnalysisRunRead;
};

export type GetAnalysisRunResponse = GetAnalysisRunResponses[keyof GetAnalysisRunResponses];

export type GetRootData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type GetRootErrors = {
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type GetRootError = GetRootErrors[keyof GetRootErrors];

export type GetRootResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
